### ISSUE TITLE
failed call to cuInit: CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE

### ISSUE THREAD

**Issue by paolovic** [google-research/omniglue#14]
Hi,

I would like to run omniglue, i have the following setup:

```bash
user@e3a1d13a6c45:/workspace$ nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:06:00.0 Off |                  N/A |
| 23%   33C    P8     9W / 250W |      0MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

```bash
user@e3a1d13a6c45:/workspace$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

still I'm getting this error

```bash
user@e3a1d13a6c45:/workspace$ python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
2024-06-07 16:13:11.692100: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-07 16:13:12.505518: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-06-07 16:13:13.476204: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:282] failed call to cuInit: CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE: forward compatibility was attempted on non supported HW
```

I did already
`pip install tensorflow[and-cuda]``

Could you help me, please?

**Comment by paolovic** [comment]
was able to resolve it like the following

* as base with cuda 11.4 (Higher cuda versions (11.8) In the dockerfile result in an error with tensorflow that complains about an unsupported HW upgrade, see above)
* Installed tensorrt 8.6.1.6 and set the LD_LIBRARY_PATH https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html
* Installed libcudnn8_8.1.1.33-1+cuda11.2_amd64.deb (cudnn 8.1.1) with “sudo dpkg -i …” and set export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
* Pip install tensorflow[and-cuda]=2.11.0
